"use strict";
let four = 4;
let nine = 9;
console.log("Test 1: Is four == 4? I predict true!");
console.log(four == 4);
console.log("Test 2: Is nine == 9? I predict true!");
console.log(nine == 9);
console.log("Test 3: Is nine != 6? I predict true!");
console.log(nine != 6);
console.log("Test 4: Is four != 9? I predict true!");
console.log(four != 9);
console.log("Test 5: Is nine != 4? I predict true!");
console.log(nine != 4);
console.log("Test 6: Is nine != 9? I predict false!");
console.log(nine != 9);
console.log("Test 7: Is four == 4? I predict false!");
console.log(four != 4);
console.log("Test 8: Is nine == 8? I predict false!");
console.log(nine == 8);
console.log("Test 9: Is four == 3? I predict false!");
console.log(four == 3);
console.log("Test 10: Is four != 4? I predict false!");
console.log(four != 4);
